from string import Template

# readme
version_data = Template('- **Version**: $version')
certified_data = Template('- **Certified**: $certify')
compatible_version_data = Template('- **Compatible Version**: FortiSOAR $compatible_version')
overview_data = Template('$overview \n\n The **Outbreak Response - $title** solution pack works with the Threat Hunt rules in [Outbreak Response Framework](https://github.com/fortinet-fortisoar/solution-pack-outbreak-response-framework/blob/release/1.0.0/README.md#threat-hunt-rules) solution pack to conduct hunts that identify and help investigate potential Indicators of Compromise (IOCs) associated with this vulnerability within operational environments of *FortiSIEM*, *FortiAnalyzer*, *QRadar*, *Splunk*, and *Azure Log Analytics*.\n\n The [FortiGuard Outbreak Page]($link) contains information about the outbreak alert **Outbreak Response - $title**.')


readme = Template('# Release Information \n\n$version_data \n$certified_data \n- **Publisher**: $publisher \n$compatible_version_data \n\n# Overview \n\n$overview \n\n## Background: \n\n$background \n\n## Announced: \n\n$announced \n\n## Latest Developments: \n\n$latest \n\n# Next Steps\n | [Installation](./$docs_name/setup.md#installation) | [Configuration](./$docs_name/setup.md#configuration) | [Usage](./$docs_name/usage.md) | [Contents](./$docs_name/contents.md) | \n |--------------------------------------------|----------------------------------------------|------------------------|------------------------------|')


# contents
content = Template('| [Home](../README.md) |\n | -------------------------------------------- |\n\n# Contents\n\nThe **Outbreak Response - $title** solution pack contains the following resources.\n\n## Outbreak Alerts Record Set\n\n| Name | Description |\n|:-------------------------|:------------------|\n| $title | $description |\n\n## Threat Hunt Rules Record set\n\n| Name | Rule Type |\n|:-------------------------|:------------------|\n$rules\n\n# Next Steps\n| [Installation](./setup.md#installation) | [Configuration](./setup.md#configuration) | [Usage](./usage.md) |\n| ----------------------------------------- | ------------------------------------------- | --------------------- |')

# usage
usage = Template('[Home](../$readme_file) |\n | -------------------------------------------- |\n\n# Usage\n\nRefer to [Simulate Scenario documentation](https://github.com/fortinet-fortisoar/solution-pack-soc-simulator/blob/develop/docs/usage.md) to understand how to simulate and reset scenarios.\n\nTo understand the process FortiSOAR follows to respond to <SP Specific threat>. We have included the following scenario with this solution pack:\n- Scenario 1\n- Scenario 2\n\nRefer to the subsequent sections to understand how this solution pack\'s automation addresses your needs.\n\n## Scenario 1\n\n## Scenario 2\n\n# Next Steps\n| [Installation](./setup.md#installation) | [Configuration](./setup.md#configuration) | [Contents](./contents.md) |\n| ----------------------------------------- | ------------------------------------------- | --------------------------- |')

# setup
setup = Template("[Home](../README.md) |\n | -------------------------------------------- |\n\n# Installation\n\n1. To install a solution pack, click **Content Hub** > **Discover**.\n2. From the list of solution pack that appears, search **Outbreak Response - $title**.\n3. Click the **Outbreak Response - $title** solution pack card.\n4. Click **Install** on the lower part of the screen to begin the installation.\n\n## Prerequisites\nThe **Outbreak Response - $title** solution pack depends on the following solution packs that are installed automatically & if not already installed.\n\n| Name                        | Type          | Version         | Purpose                                |\n|:----------------------------|:--------------|:----------------|:---------------------------------------|\n| SOAR Framework              | Solution Pack | v2.2.0 or later | Required for Incident Response modules |\n| Threat Intel Management     | Solution Pack | v1.1.0 or later | Required to ingest threat feeds        |\n| Vulnerability Management    | Solution Pack | v1.2.1 or later | Required to ingest CVEs for KEVs       |\n| Outbreak Response Framework | Solution Pack | v1.0.0 or later | Helps in investigating Vulnerability.  |\n\n# Configuration\n\nAfter configuration wizard on the *Outbreak Response Framework* solution pack is complete; no configuration is required for this SP.\n\n# Next Steps\n| [Usage](./usage.md) | [Contents](./contents.md) |\n|---------------------|---------------------------|")

# usage
usage = Template("[Home](../README.md) |\n| -------------------------------------------- |\n\n# Usage\n\nTo investigate the alert, perform the following steps:\n\n1. Under the FortiSOAR&trade;'s left navigation panel, select **Outbreak Management** > **Outbreak Alerts**.\n2. Open the record **$title**.\n3. Click the button **Execute**.\n4. Select **Investigate Outbreak** on the outbreak alert's screen to start the investigation.\n\n# Next Steps\n\n| [Installation](./setup.md#installation) | [Configuration](./setup.md#configuration) | [Contents](./contents.md) |\n|-----------------------------------------|-------------------------------------------|---------------------------|")