EXCLUDE_RECORD_SETS = ['fsr_queues', 'sla_template']
README_FILE_NAME = 'README.md'
CONTENTS_FILE_NAME = 'contents.md'
SETUP_FILE_NAME = 'setup.md'
USAGE_FILE_NAME = 'usage.md'
RELEASE_NOTE_FILE_NAME = 'release_notes.md'
DOC_FOLDER_NAME = 'docs'
RESOURCE_FOLDER_NAME = 'res'
FORTISOAR_CONNECTOR_DOC_API = 'https://docs.fortinet.com/api/connectors'
FORTISOAR_CONNECTOR_DOC_LINK = 'https://docs.fortinet.com/fortisoar/connectors/'
OLD_SP_INFO_JSON_DATA = 'https://raw.githubusercontent.com/fortinet-fortisoar/{sp_repo_name}/{branch_name}/info.json'
OLD_SP_PLAYBOOK_COLLECTION_DATA = 'https://api.github.com/repos/fortinet-fortisoar/{sp_repo_name}/contents/playbooks/{playbook_collection_name}?ref={branch_name}'
OLD_SP_DOC_DATA = 'https://api.github.com/repos/fortinet-fortisoar/{sp_repo_name}/contents/{folder_to_copy}?ref={branch_name}'
